### ISSUE TITLE
what is different between minko_knn_cbam_fast.py and minko_knn_cbam.py?

### ISSUE THREAD

**Issue by Yellowshuohahaha** [grgzam/Attention_Mechanisms_for_3D_Semantic_Segmentation#1]
I trained them separately, but it seems that the training time for minko_knn_cbam_fast.py did not decrease.

**Comment by grgzam** [comment]
Indeed the training time should be the same. 
The models with the "fast" abbreviation, should be slightly faster during the inference of the scenes, not during training.
We have observed this on our hardware setup.
However, this might not hold for all hardware setups.

**Comment by Yellowshuohahaha** [comment]
> Indeed the training time should be the same. The models with the "fast" abbreviation, should be slightly faster during the inference of the scenes, not during training. We have observed this on our hardware setup. However, this might not hold for all hardware setups.

Thanks for your reply!
